# Generated by Django 2.0.7 on 2018-07-09 09:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mdm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestOfferModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(default=django.utils.timezone.now)),
                ('duration', models.IntegerField(blank=True, default=0, null=True)),
                ('lowest_price', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('bag_weight', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('bag_price', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('arrival', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='mdm.AirportModel')),
                ('departure', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='mdm.AirportModel')),
                ('market', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mdm.MarketModel')),
                ('supplier', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mdm.SupplierModel')),
            ],
        ),
    ]
