# Generated by Django 2.1 on 2018-08-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirportModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('display_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'mdm_airports',
                'verbose_name': 'Airport',
                'verbose_name_plural': 'Airports',
            },
        ),
        migrations.CreateModel(
            name='BagTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('weight', models.IntegerField()),
                ('display_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'mdm_bagtype',
                'verbose_name': 'Bagtype',
                'verbose_name_plural': 'Bagtypes',
            },
        ),
        migrations.CreateModel(
            name='BoardModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('display_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'mdm_boards',
                'verbose_name': 'Board',
                'verbose_name_plural': 'Boards',
            },
        ),
        migrations.CreateModel(
            name='FlightProviderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('display_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'mdm_flightprovider',
                'verbose_name': 'Flight provider',
                'verbose_name_plural': 'Flight providers',
            },
        ),
        migrations.CreateModel(
            name='HotelModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('display_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=2000, null=True)),
                ('stars', models.IntegerField()),
            ],
            options={
                'db_table': 'mdm_hotels',
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
            },
        ),
        migrations.CreateModel(
            name='MarketModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('display_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'mdm_markets',
                'verbose_name': 'Market',
                'verbose_name_plural': 'Markets',
            },
        ),
        migrations.CreateModel(
            name='RoomTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('display_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'mdm_roomtypes',
                'verbose_name': 'Roomtype',
                'verbose_name_plural': 'Roomtypes',
            },
        ),
        migrations.CreateModel(
            name='SupplierModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('display_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=2000, null=True)),
                ('portal', models.URLField(max_length=2000)),
            ],
            options={
                'db_table': 'mdm_suppliers',
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
            },
        ),
    ]
