# Generated by Django 2.0.7 on 2018-07-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirportModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('display_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'mdm_airports',
            },
        ),
        migrations.CreateModel(
            name='BagTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('display_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoardModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('display_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'mdm_boards',
            },
        ),
        migrations.CreateModel(
            name='FlightProviderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('display_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HotelModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField()),
                ('display_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'mdm_hotels',
            },
        ),
        migrations.CreateModel(
            name='MarketModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('display_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'mdm_markets',
            },
        ),
        migrations.CreateModel(
            name='RoomTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('display_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'mdm_roomtypes',
            },
        ),
        migrations.CreateModel(
            name='SupplierModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal', models.URLField(max_length=2000)),
                ('display_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'mdm_suppliers',
            },
        ),
    ]
