# Generated by Django 2.1 on 2018-08-28 17:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArgumentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100)),
                ('friendly_name', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=1000)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean')], default='text', max_length=30)),
                ('default_value', models.CharField(blank=True, default=None, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Argument',
                'verbose_name_plural': 'Arguments',
            },
        ),
        migrations.CreateModel(
            name='ExecutionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('ended', models.DateTimeField(blank=True, default=None, null=True)),
                ('configuration', models.TextField(default='{}', max_length=1000)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed'), ('paused', 'Paused'), ('pending', 'Pending'), ('running', 'Running')], default='pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100)),
                ('friendly_name', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=1000)),
                ('active', models.BooleanField(default=True)),
                ('notebook', models.FilePathField(max_length=500, path='/home/lordoftheflies/Documents/theoutsourcepro/gargantula/scrapersite/../notebooks')),
            ],
            options={
                'verbose_name': 'Process',
                'verbose_name_plural': 'Processes',
            },
        ),
        migrations.AddField(
            model_name='executionmodel',
            name='process',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='engine.ProcessModel'),
        ),
        migrations.AddField(
            model_name='argumentmodel',
            name='process',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arguments', to='engine.ProcessModel'),
        ),
    ]
