# Generated by Django 2.1 on 2018-08-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_auto_20180828_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argumentmodel',
            name='data_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean'), ('enumeration_airport', 'Airports'), ('enumeration_bagtype', 'Bag type'), ('enumeration_board', 'Board'), ('enumeration_flightsupplier', 'Flight supplier'), ('enumeration_hotel', 'Hotel'), ('enumeration_market', 'Market'), ('enumeration_roomtype', 'Room type'), ('enumeration_supplier', 'Supplier')], default='text', max_length=30),
        ),
    ]
