# Generated by Django 2.1 on 2018-08-29 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_auto_20180828_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100)),
                ('friendly_name', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=1000)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean'), ('enumeration_airport', 'Airports'), ('enumeration_bagtype', 'Bag type'), ('enumeration_board', 'Board'), ('enumeration_flightprovider', 'Flight provider'), ('enumeration_hotel', 'Hotel'), ('enumeration_market', 'Market'), ('enumeration_roomtype', 'Room type'), ('enumeration_supplier', 'Supplier')], default='text', max_length=30)),
                ('default_value', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('tag', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('process', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schema', to='engine.ProcessModel')),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'verbose_name': 'Property',
            },
        ),
        migrations.AlterField(
            model_name='argumentmodel',
            name='data_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean'), ('enumeration_airport', 'Airports'), ('enumeration_bagtype', 'Bag type'), ('enumeration_board', 'Board'), ('enumeration_flightprovider', 'Flight provider'), ('enumeration_hotel', 'Hotel'), ('enumeration_market', 'Market'), ('enumeration_roomtype', 'Room type'), ('enumeration_supplier', 'Supplier')], default='text', max_length=30),
        ),
    ]
