# Generated by Django 2.1 on 2018-09-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_eventmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionmodel',
            name='status',
            field=models.CharField(choices=[('initial', 'Initial'), ('completed', 'Completed'), ('failed', 'Failed'), ('paused', 'Paused'), ('pending', 'Pending'), ('running', 'Running')], default='initial', max_length=50),
        ),
    ]
